CREATE TABLE police_officers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    rank VARCHAR(50),
    g_number VARCHAR(50),
    station VARCHAR(100),
    date_of_enlistment DATE,
    date_of_promotion DATE,
    date_of_birth DATE,
    cps_number VARCHAR(50),
    ifhrms_number VARCHAR(50),
    contact_number VARCHAR(20),
    father_name VARCHAR(100),
    marital_status VARCHAR(20),
    spouse_name VARCHAR(100),
    permanent_address TEXT,
    present_address TEXT,
    bank_name VARCHAR(100),
    account_number VARCHAR(50),
    ifsc_code VARCHAR(20),
    branch VARCHAR(100),
    aadhar_number VARCHAR(20),
    pan_number VARCHAR(20),
    religion VARCHAR(50),
    community VARCHAR(50),
    caste VARCHAR(50),
    education TEXT,
    blood_group VARCHAR(5),
    present_station_name VARCHAR(100),
    present_station_join_date DATE,
    previous_station_name VARCHAR(100),
    previous_station_join_date DATE,
    previous_station_end_date DATE,
    photo_type VARCHAR(20),
    photo_path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);